### ISSUE TITLE
Update Natural Gas Spot Prices

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#212]
### Feature Request

The [Henry Hub](https://ycharts.com/indicators/henry_hub_natural_gas_spot_price) has daily prices on natural gas, while EIA only gives monthly. Doesnt seem like HH gives a breakdown by state or industry, but we could maybe look at using HH profiles

**Comment by ktehranchi** [comment]
I'm not sure if you saw my PR from earlier in the week. I have added a module for build_fuel_prices which pulls in CAISO WECC fuel prices. I think we should try to pull in natural gas prices from ISO's, since they should all have an interface for daily historical regional prices.....

Also was thinking we should pull in Annual Energy Outlook for future expected NG prices for scenario analysis

**Comment by trevorb1** [comment]
@ktehranchi, totally agree with the ISO point! Def relates to issue #206. 

On the AEO for NG prices, you mean like scale the annual average cost of NG in the modelled year with the projected year in the AEO? The [AEO seems to only have yearly prices](https://www.eia.gov/outlooks/aeo/data/browser/#/?id=13-AEO2023&cases=ref2023&sourcekey=0) (but maybe I am just missing seeing it!). And I think ensuring we keep as fine temporal resolution as we can for NG prices will be important to better represent capacity services! I like the idea of scaling everything if we can only get yearly data!

**Comment by trevorb1** [comment]
They do have daily regional natural gas spot prices [here](https://www.eia.gov/todayinenergy/prices.php). Not sure of a way to programatically access them, though.

**Comment by ktehranchi** [comment]
The closing issue with the implementation of PuDL fuel receipts, which provides better coverage of fuel prices paid by generators. #361
