### ISSUE TITLE
Unnecessary Param Definition

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#459]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

Why do we need to have planning_horizons as a param to build_base_network?

```
    # add snapshots
    sns_config = snakemake.params.snapshots
    planning_horizons = snakemake.params.planning_horizons

    n.snapshots = get_multiindex_snapshots(sns_config, planning_horizons)
    n.set_investment_periods(periods=planning_horizons)
```

It is only used at the end to set the horizon.... but this means if the user wants to edit the planning horizons in the model, they end up triggering all rules downstream of build_base_network. If we move that code segment to build_demand then we remove the need to unnecessary running of `build_renewable_profiles` which is the longest running step.

@trevorb1 thoughts? any reason to keep this in build_base_network?

**Comment by trevorb1** [comment]
Fine by me to move the investment periods as far down the workflow as possible! Good call. 

My only note is that I think it should get added to the network in `add_demand` rather than `build_demand`, as `build_demand` doesnt actually write out a network file. With that said, I believe (although I would need to double check) that the `DemandFormatter`, which is used to scale demand, directly uses the property `n.investment_periods`. So we may just need to assign investment periods temporarily in `build_demand` and then for real in `add_demand`. Or modify `DemandFormatter` to use an investment periods list as a parameter.
